# Generated by Django 3.2.23 on 2024-02-29 12:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cnc_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('place_id', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('purpose', models.IntegerField()),
                ('documentation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cnc_machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.IntegerField()),
                ('place_id', models.IntegerField()),
                ('purpose', models.IntegerField()),
                ('price', models.IntegerField()),
                ('documentation', models.IntegerField()),
                ('qr', models.IntegerField()),
                ('buy_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cnc_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('machine_id', models.IntegerField()),
                ('place_id', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('material_id', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('amount_material', models.IntegerField()),
                ('production_time', models.IntegerField()),
                ('production_date', models.IntegerField()),
                ('cnc_detail_id', models.IntegerField()),
                ('cnc_detail_documentation', models.IntegerField()),
                ('qr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('purpose', models.IntegerField()),
                ('place_id', models.IntegerField()),
                ('shop', models.IntegerField()),
                ('buy_date', models.IntegerField()),
                ('price', models.IntegerField()),
                ('qr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('place_id', models.IntegerField()),
                ('color', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('structure', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('buy_date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('rate', models.FloatField()),
                ('measurement_unit', models.CharField(max_length=20)),
                ('measurement_date', models.DateField(default=datetime.datetime)),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=256)),
                ('rent', models.IntegerField(default=0)),
                ('square', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('place_id', models.IntegerField()),
                ('purpose', models.TextField(default='-', help_text='Введите назначение датчика')),
                ('price', models.IntegerField(default='0')),
                ('shop_url', models.URLField(default='Not Found', max_length=256)),
                ('documentation', models.URLField(default='Not Found', max_length=256)),
                ('qr', models.URLField(default='-', max_length=256)),
                ('buy_date', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='measurements',
        ),
        migrations.AddField(
            model_name='measurement',
            name='place_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='office.place'),
        ),
    ]
