# Generated by Django 3.2.23 on 2024-02-29 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20240229_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 12, 26, 6, 146)),
        ),
    ]
