# Generated by Django 3.2.23 on 2024-02-29 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_alter_measurement_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 12, 27, 54, 232429, tzinfo=utc)),
        ),
    ]
