# Generated by Django 3.2.23 on 2024-02-29 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_alter_measurement_measurement_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
