# Generated by Django 3.2.23 on 2024-02-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField(verbose_name='Объем л или кг')),
                ('initial_temperature', models.FloatField(verbose_name='Начальная температура °C')),
                ('target_temperature', models.FloatField(verbose_name='Конечная температура °C')),
                ('efficiency', models.FloatField(default=100, verbose_name='КПД %')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(default=2.0)),
                ('width', models.FloatField(default=1.0)),
                ('wall_thickness', models.FloatField(default=0.1)),
                ('temperature_udel', models.FloatField(default=0.028)),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
